Repository NECC/NECChange, pull requests merged in 2023-07, with the labels that each got.

#10 api route to get classes
  necchange/.env
  necchange/app/api/trades/student_schedule/[student_nr]/route.js
  necchange/app/components/trades/schedule/StudentSchedule.jsx
  necchange/app/trades/page.jsx
  necchange/package-lock.json
  necchange/package.json
  necchange/tsconfig.json
Labels: trocas, api

#29 Sq/submit trades
  necchange/app/api/feed/feed_post/route.ts
  necchange/app/api/trades/shifts/[...student_data]/route.ts
  necchange/app/components/globals/navbar/NavbarLinks.tsx
  necchange/app/components/trades/popUp/PopUp.tsx
  necchange/app/components/trades/trades/Trades.tsx
  necchange/app/trades/page.tsx
  necchange/package-lock.json
  necchange/package.json
  necchange/prisma/migrations/20230717104428_changed_time_fields_on_switch/migration.sql
  necchange/prisma/migrations/20230717104959_added_status_to_switch/migration.sql
  necchange/prisma/migrations/20230719223919_changed_switch_table/migration.sql
  necchange/prisma/migrations/20230719231123_string_to_date_on_switch_table/migration.sql
  necchange/prisma/schema.prisma
  necchange/tailwind.config.js
Labels: trocas, api

#30 Pc/feed filter
  necchange/app/components/trades/feed-posts/FeedPosts.tsx
  necchange/app/components/trades/filters/Filters.tsx
  necchange/app/components/trades/filters/UCFilter.tsx
  necchange/app/components/trades/filters/YearFilter.tsx
  necchange/app/components/trades/filters/interface.ts
  necchange/app/feed/page.tsx
Labels: trocas

#31 Pc/feed filter
  necchange/app/components/trades/feed-posts/FeedPosts.tsx
  necchange/app/components/trades/filters/Filters.tsx
  necchange/app/components/trades/filters/UCFilter.tsx
  necchange/app/feed/interface.ts
  necchange/app/feed/page.tsx
Labels: trocas

#32 Loading.tsx
  necchange/app/calendar/loading.tsx
  necchange/app/feed/loading.tsx
  necchange/app/trades/loading.tsx
Labels: trocas, calendario

#27 Pc/feed
  necchange/app/api/feed/feed_post/[...scroll]/route.ts
  necchange/app/api/feed/feed_post/add_trade/interface.ts
  necchange/app/api/feed/feed_post/add_trade/route.ts
  necchange/app/api/feed/feed_post/landing/[limit]/route.ts
  necchange/app/api/trades/shifts/[...student_data]/route.ts
  necchange/app/api/trades/student_schedule/[student_nr]/route.js
  necchange/app/calendar/loading.tsx
  necchange/app/components/globals/navbar/NavbarLinks.tsx
  necchange/app/components/trades/feed-posts/FeedPost.tsx
  necchange/app/components/trades/filters/Filters.tsx
  necchange/app/components/trades/filters/UCFilter.tsx
  necchange/app/components/trades/filters/YearFilter.tsx
  necchange/app/components/trades/filters/interface.ts
  necchange/app/components/trades/popUp/PopUp.tsx
  necchange/app/components/trades/popUp/interface.ts
  necchange/app/components/trades/schedule/StudentSchedule.tsx
  necchange/app/components/trades/schedule/interface.ts
  necchange/app/components/trades/trades/Trades.tsx
  necchange/app/components/trades/trades/interface.ts
  necchange/app/feed/interface.ts
  necchange/app/feed/loading.tsx
  necchange/app/feed/page.tsx
  necchange/app/globals.css
  necchange/app/horario/interface.ts
  necchange/app/horario/loading.tsx
  necchange/app/horario/page.tsx
  necchange/package-lock.json
  necchange/package.json
  necchange/prisma/migrations/20230717104428_changed_time_fields_on_switch/migration.sql
  necchange/prisma/migrations/20230717104959_added_status_to_switch/migration.sql
  necchange/prisma/migrations/20230719223919_changed_switch_table/migration.sql
  necchange/prisma/migrations/20230719231123_string_to_date_on_switch_table/migration.sql
  necchange/prisma/migrations/20230720013142_changed_switch_table/migration.sql
  necchange/prisma/migrations/20230720013949_made_optional_fields_on_switch/migration.sql
  necchange/prisma/migrations/20230723154712_add_trade_tabl/migration.sql
  necchange/prisma/schema.prisma
  necchange/prisma/seed.ts
  necchange/tailwind.config.js
Labels: trocas
